### ISSUE TITLE
The returned best_classifier 

### ISSUE THREAD

**Issue by Bee-zest** [microsoft/fairlearn#3]
When I used the returned best_classifier to do prediction. The prediction scores are binary not probability based. How could I generate the probability based prediction? Thanks

**Comment by MiroDudik** [comment]
If the question is about interpreting the output of `best_classifier`, please see #5 .

However, I am assuming that your question is about optimizing a loss other than **misclassification error**, for example, when training a logistic regression model to optimize likelihood.

Our method currently only handles misclassification error. If you’re interested in optimizing more general objectives under fairness constraints, one of these papers might be helpful:

* [Alabi et al. 2018](http://proceedings.mlr.press/v75/alabi18a/alabi18a.pdf)
* [Narasimhan 2018](http://proceedings.mlr.press/v84/narasimhan18a/narasimhan18a.pdf)
* [Cotter et al. 2019](http://proceedings.mlr.press/v97/cotter19b/cotter19b.pdf)
* [Agarwal et al. 2019](http://proceedings.mlr.press/v97/agarwal19d/agarwal19d.pdf)

**Comment by Bee-zest** [comment]
Thanks. Would you publish the code in fair regression paper?

**Comment by romanlutz** [comment]
There are multiple algorithms in that paper. Which one are you referring to?

**Comment by romanlutz** [comment]
Actually, that's a different issue. Can you open a new one so that we can track this properly?
