### ISSUE TITLE
ModuleNotFoundError: No module named 'azureml.contrib.explain'

### ISSUE THREAD

**Issue by gabrielarcangelbol** [microsoft/fairlearn#78]
Hi guys,

I am testing the tool using the Threshold Optimization Post-Processing for Binary notebook and i am continuously getting the following error:

![image](https://user-images.githubusercontent.com/45678322/66514119-864c5480-eaaa-11e9-9b3e-afe8f1d01fe6.png)

I read about a similar issue and they recommend to:
pip install 'azureml-sdk[notebooks]'
But i get the same error.
Could you let me know what i could do? Please

**Comment by riedgar-ms** [comment]
How did you install the `FairnessDashboard` ? You should be doing something like:

pip install 'azureml-contrib-explain-model<=0.1.50' --extra-index-url 'https://azuremlsdktestpypi.azureedge.net/azureml-core-run-submit-tests/5132569'

The `FairnessDashboard` is very much in preview right now (everything is subject to change), hence the unusual installation method.

**Comment by gabrielarcangelbol** [comment]
I tried to install the package as you suggested: azureml-contrib-explain-model<=0.1.50 But  The system cannot find the file specified.

When i show the azureml-contrib-explain-model, i have installed the oldest available one:

![image](https://user-images.githubusercontent.com/45678322/66520785-d4b42000-eab7-11e9-8ad2-4995baa1a510.png)

**Comment by gabrielarcangelbol** [comment]
Ok, thanks!

**Comment by SameerKSharma** [comment]
Is there an expected timeline for when the DashBoard will be available to the public?
